config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/new'
  post 'users', to: 'users#create'
  delete 'users/:id', to: 'user#destroy'
  get 'top/main'
  post 'top/login'
  root 'top#main'
  get 'top/logout'
  resources :users, only: [:index, :new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, :pass, presence: true
    
    def self.authenticate(uid,pass)
        user = find_by(uid: uid)
        if user and BCrypt::Password.new(user.pass) == pass
            true
        else
            false
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def L4
        session[:c] ||=0
        session[:c] = session[:c].to_i + 1
        render plain: session[:c]
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid]
      render :main
    else
      render :login
    end
  end
  
  def login
    if User.authenticate(params[:uid],params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to root_path
    else
      render :error
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    pass = BCrypt::Password.create(params[:user][:pass])
    @user = User.new(uid: params[:user][:uid], pass: pass)
    if @user.save
      flash[:info] = 'ユーザー登録に成功しました'
      redirect_to users_path
    else
      @user.pass = ""
      render :new
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:info] = 'ユーザー削除に成功しました'
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
ログイン失敗です。
<p>
<%= link_to '戻る' , :back %>
</p>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <p>
        <%= label_tag :uid, 'ユーザーID' %>
        <%= text_field_tag :uid %>
    </p>
    <p>
        <%= label_tag :pass, 'パスワード' %>
        <%= password_field_tag :pass %>
    </p>
    <p>
        <%= submit_tag 'ログイン' %>
    </p>
    <p>
        <%= link_to 'ユーザー登録','/users/new' %>
    </p>
<% end %>

app/views/top/main.html.erb
ログイン中です

<%= link_to 'ログアウト', top_logout_path %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% if flash[:info] %>
 <font color="green"><%= flash[:info] %></font>
<% end %>

<% @users.each do |e| %>
 <p>
  <%= e.uid %>
  <%= link_to '削除', user_path(e), method: :delete %>
 </p>
<% end %>

<hr>

<%= link_to 'ユーザー追加', new_user_path %>

app/views/users/new.html.erb
<%= form_for @user ,url:{action: :create} do |f| %>
 <%= f.label :uid, 'ユーザーID' %>
 <%= f.text_field :uid %>
 <%= f.label :pass, 'パスワード' %>
 <%= f.text_field :pass %>
 <%= f.submit '登録' %>
<% end %>